name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: shards install

    - name: spec
      run: crystal spec

    - name: lint
      run: crystal tool format --check
